"""migrate posts and comments

Revision ID: 91e447f104f3
Revises: 38601a43b313
Create Date: 2026-07-26 17:20:38.146084

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "91e447f104f3"
down_revision: Union[str, Sequence[str], None] = "38601a43b313"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("comments_post_id_fkey"), "comments", type_="foreignkey")
    op.create_foreign_key(
        None, "comments", "posts", ["post_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "comments", type_="foreignkey")
    op.create_foreign_key(
        op.f("comments_post_id_fkey"), "comments", "posts", ["post_id"], ["id"]
    )
    # ### end Alembic commands ###
